### ISSUE TITLE
suggestion / add more mob types with higher version of mc mobs

### ISSUE THREAD

**Issue by adalmo** [theabdel572/MobKillsCounter#4]
is this pl going to support 1.19.4?

**Comment by abdelachbani** [comment]
Have you tested it in that version?

**Comment by adalmo** [comment]
not yet because spigot site supporting version said the latest is 1.16 but i can test it

**Comment by abdelachbani** [comment]
yeah, that's the versions that i've tested, feel free to test it in 1.19, and if u want tell me if it works so i can add it to the tested versions

**Comment by adalmo** [comment]
yep it works fine on 1.19.4 but some mobs are missing like piglin & warden https://pastebin.com/wHFmhjLx (it's showing this error msg) i hope u can add em later (also is it normal is the plugin doesn't count kills before i install this pl?)

**Comment by abdelachbani** [comment]
Hey, ty for testing it. Yeah, some mobs are missing because the plugin is made natively in 1.8, to make it compatible with the most possible versions, and the jar of that version doesn't contain EntityTypes of newer versions (that's also why the error happens, cause you are killing newer version entities). But now, i just saw the way that i've recoded the plugin, and i think it would be possible to add newer version mobs even using the 1.8 jar, i will test this and update this issue.

Also yeah, it's normal that the plugin doesn't count kills that are made before the installation. That's because the plugin has it's own kills storage system found in the players.yml file.

**Comment by abdelachbani** [comment]
Just tested, and with the new system i've released, the plugin is able to support newer version mobs with the native 1.8 jar.
I'm adding some newer mobs in the next release [wardens, allays, axolotles, bees, and all the newer versions piglins (normal, brute, and zombified)].
Thank you for reporting and testing the plugin.

**Comment by adalmo** [comment]
v2.2 missed polar bear & drown & tropical fish and more

**Comment by abdelachbani** [comment]
> v2.2 missed polar bear & drown & tropical fish and more

I haven't planned adding every single minecraft mob for the moment.
